# Site settings
title: Run Bike Run Tilburg
email: armand.van.der.smissen@triathlonbond.nl
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
